using ITensors,
      Test

include("test_tagset.jl")
include("test_index.jl")
include("test_indexset.jl")
include("test_itensor.jl")
include("test_contract.jl")
include("test_trg.jl")
include("test_ctmrg.jl")
include("test_siteset.jl")
include("test_mps.jl")
include("test_mpo.jl")
include("test_autompo.jl")
include("test_svd.jl")
include("test_cucontract.jl")
include("test_cuitensor.jl")
include("test_cumps.jl")
include("test_cumpo.jl")
#include("test_trg.jl")
#include("test_ctmrg.jl")
