name: Run benchmarks

on:
  pull_request:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - name: Install dependencies
        shell: julia --project=benchmark/ {0}
        run: |
          using Pkg;
          pkg"add PkgBenchmark BenchmarkCI@0.1";
          pkg"dev NDTensors ."
      - name: Run benchmarks
        run: julia --project=benchmark/ -e 'using Pkg; using BenchmarkCI; BenchmarkCI.judge(; baseline="origin/main")'
      - name: Post results
        run: julia -e 'using BenchmarkCI; BenchmarkCI.postjudge()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
