name: "CheckCompatBoundsNDTensors"
on:
  pull_request:
    paths:
      - "NDTensors/**"
permissions:
  contents: "read"
jobs:
  check-compat-bounds:
    name: "CheckCompatBoundsNDTensors"
    uses: "ITensor/ITensorActions/.github/workflows/CheckCompatBounds.yml@mf/subdir-inputs"
    with:
      subdir: "NDTensors"
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
