name: "CheckCompatBounds"
on:
  pull_request: ~
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ startsWith(github.ref, 'refs/pull/') }}"
permissions:
  contents: "read"
jobs:
  check-compat-bounds:
    name: "CheckCompatBounds"
    uses: "ITensor/ITensorActions/.github/workflows/CheckCompatBounds.yml@v2"
    with:
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
