name: Run ITensors mps tests from comment trigger

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.threads }} thread(s)
    runs-on: ${{ matrix.os }}
    env:
      JULIA_NUM_THREADS: ${{ matrix.threads }}
    strategy:
      matrix:
        version:
          - '1.6'
          - '1'
        os:
          - ubuntu-latest
        threads:
          - '2'
        arch:
          - x64
        exclude:
          # MacOS not available on x86
          - {os: 'macOS-latest', arch: 'x86'}
    steps:
      - name: Pull Request Comment Trigger
        uses: Khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '[mps]'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v2
        if: steps.check.outputs.triggered == 'true'
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
        if: steps.check.outputs.triggered == 'true'
      - name: Install Julia dependencies
        shell: julia --project=monorepo {0}
        run: |
          using Pkg;
          pkg"dev ./NDTensors ."
        if: steps.check.outputs.triggered == 'true'
      - name: Run the tests
        shell: julia --project=monorepo {0}
        run: |
          using Pkg;
          # https://github.com/JuliaLang/Pkg.jl/pull/1226
          Pkg.test("ITensors"; coverage=true, test_args=["mps"])
        if: steps.check.outputs.triggered == 'true'
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: steps.check.outputs.triggered == 'true'
