name: Comment Trigger
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Comment Trigger
        uses: Khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '[comment trigger]'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo [comment trigger] trigger detected.'
        if: steps.check.outputs.triggered == 'true'
