name: "Documentation"
on:
  push:
    branches:
      - "main"
    tags: ["v*"]
  pull_request: ~
  schedule:
    - cron: "1 4 * * 4"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}"
permissions:
  contents: "write"
jobs:
  documentation:
    name: "Documentation"
    uses: "ITensor/ITensorActions/.github/workflows/Documentation.yml@mf/subdir-inputs"
    with:
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
