name: Format check
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  format:
    name: "Format Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
      - name: Install JuliaFormatter and format
        run: |
          julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter"))'
          julia  -e 'using JuliaFormatter; format(".", verbose=true)'
      - name: Check format
        run: |
          julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "The following files have not been formatted:"
              write(stdout, out)
              out_diff = Cmd(`git diff`) |> read |> String
              @error "Diff:"
              write(stdout, out_diff)
              exit(1)
              @error ""
          end'
