name: "FormatCheck"
on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "ready_for_review"
permissions:
  contents: "read"
jobs:
  format-check:
    name: "FormatCheck"
    uses: "ITensor/ITensorActions/.github/workflows/FormatCheck.yml@v2"
