name: "FormatCheckComment"
on:
  workflow_run:
    workflows:
      - "FormatCheck"
    types:
      - "completed"
permissions:
  pull-requests: "write"
  actions: "read"
jobs:
  format-check-comment:
    name: "FormatCheckComment"
    if: "github.event.workflow_run.event == 'pull_request'"
    uses: "ITensor/ITensorActions/.github/workflows/FormatCheckComment.yml@v2"
    secrets: "inherit"
