name: "IntegrationTestNDTensors"
on:
  push:
    branches:
      - "main"
    tags: "*"
    paths:
      - "NDTensors/**"
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "ready_for_review"
      - "converted_to_draft"
    paths:
      - "NDTensors/**"
permissions:
  actions: "read"
  contents: "read"
jobs:
  integration-test:
    name: "IntegrationTestNDTensors"
    uses: "ITensor/ITensorActions/.github/workflows/IntegrationTest.yml@mf/subdir-inputs"
    secrets: "inherit"
    with:
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
      subdir: "NDTensors"
      pkgs: |
        [
          "ITensors",
          "ITensorGaussianMPS",
          "ITensorMPS",
          "ITensorNetworks",
          "ITensorUnicodePlots",
          "ITensorVisualizationBase",
          "https://github.com/ITensor/Tennis.jl"
        ]
