name: "Integration Test Request"
on:
  issue_comment:
    types:
      - "created"
permissions:
  actions: "read"
  contents: "read"
  checks: "write"
  pull-requests: "write"
jobs:
  integrationrequest:
    if: |
      github.event.issue.pull_request &&
      contains(fromJSON('["OWNER", "COLLABORATOR", "MEMBER"]'), github.event.comment.author_association)

    uses: "ITensor/ITensorActions/.github/workflows/IntegrationTestRequest.yml@v1"
    secrets: "inherit"
    with:
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
