name: "IntegrationTest"
on:
  push:
    branches:
      - "main"
    tags: "*"
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "ready_for_review"
      - "converted_to_draft"
jobs:
  integration-test:
    name: "IntegrationTest"
    uses: "ITensor/ITensorActions/.github/workflows/IntegrationTest.yml@v1"
    secrets: "inherit"
    with:
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
      extra-dev-paths: "NDTensors"
      pkgs: |
        [
          "ITensorGaussianMPS",
          "ITensorMPS",
          "ITensorNetworks",
          "ITensorUnicodePlots",
          "ITensorVisualizationBase",
          "https://github.com/ITensor/Tennis.jl"
        ]
          
