name: "Run ITensors base tests (macOS and Windows)"
on:
  push:
    branches:
      - "main"
  pull_request: ~
permissions:
  contents: "read"
jobs:
  test:
    name: "Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.threads }} thread(s)"
    runs-on: "${{ matrix.os }}"
    env:
      JULIA_NUM_THREADS: "${{ matrix.threads }}"
    strategy:
      fail-fast: false
      matrix:
        version: ${{ github.event_name == 'pull_request' && fromJSON('["1"]') || fromJSON('["lts","1"]') }}
        os:
          - "macOS-latest"
          - "windows-latest"
        threads:
          - "2"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "julia-actions/setup-julia@v3"
        with:
          version: "${{ matrix.version }}"
      - name: "Install Julia dependencies and run tests"
        shell: "julia {0}"
        run: |
          using Pkg;
          Pkg.activate(temp=true);
          Pkg.develop(path="./NDTensors");
          Pkg.develop(path=".");
          Pkg.test("ITensors"; coverage=true, test_args=["base"]);
      - uses: "codecov/codecov-action@v5"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
