name: Run ITensors mps tests on push to main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.threads }} thread(s)
    runs-on: ${{ matrix.os }}
    env:
      JULIA_NUM_THREADS: ${{ matrix.threads }}
    strategy:
      matrix:
        version:
          - '1.6'
          - '1'
        os:
          - ubuntu-latest
        threads:
          - '2'
        arch:
          - x64
        exclude:
          # MacOS not available on x86
          - {os: 'macOS-latest', arch: 'x86'}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Install Julia dependencies
        shell: julia --project=monorepo {0}
        run: |
          using Pkg;
          Pkg.develop(path="./NDTensors");
          Pkg.develop(path=".");
      - name: Run the tests
        shell: julia --project=monorepo {0}
        run: |
          using Pkg;
          # https://github.com/JuliaLang/Pkg.jl/pull/1226
          Pkg.test("ITensors"; coverage=true, test_args=["mps"])
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
