name: Register Package
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    paths:
      - 'Project.toml'
    branches:
      - 'master'
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  Register:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: "ITensor/ITensorActions/.github/workflows/Registrator.yml@main"
    with:
      localregistry: ITensor/ITensorRegistry
    secrets:
      REGISTRATOR_KEY: ${{ secrets.REGISTRATOR_KEY }}
