name: "Registrator"
on:
  workflow_dispatch: ~
  push:
    branches:
      - "main"
    paths:
      - "Project.toml"
  issue_comment:
    types:
      - "created"
permissions:
  contents: "write"
  pull-requests: "write"
  issues: "write"
jobs:
  registrator:
    name: "Registrator"
    uses: "ITensor/ITensorActions/.github/workflows/Registrator.yml@v2"
    secrets: "inherit"
