name: "TagBot"
on:
  issue_comment:
    types:
      - "created"
  workflow_dispatch: ~
env:
  REGISTRY_TAGBOT_ACTION: "JuliaRegistries/TagBot"
jobs:
  TagBot:
    if: "github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'"
    uses: "ITensor/ITensorActions/.github/workflows/TagBot.yml@v1"
    with:
      subdirs: '["NDTensors"]'
    secrets: "inherit"
