name: Run ITensorMPS tests (Ubuntu)

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.threads }} thread(s)
    runs-on: ${{ matrix.os }}
    env:
      JULIA_NUM_THREADS: ${{ matrix.threads }}
    strategy:
      matrix:
        version:
          - 'lts'
          - '1'
        os:
          - ubuntu-latest
        threads:
          - '2'
        arch:
          - x64
        exclude:
          # MacOS not available on x86
          - {os: 'macOS-latest', arch: 'x86'}
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Install Julia dependencies and run tests
        shell: julia {0}
        run: |
          using Pkg;
          Pkg.activate(temp=true);
          Pkg.develop(path="./NDTensors");
          Pkg.develop(path=".");
          # https://github.com/JuliaLang/Pkg.jl/pull/1226
          Pkg.test("ITensors"; coverage=true, test_args=["mps"]);
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
