name: "VersionCheckNDTensors"
on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "ready_for_review"
permissions:
  contents: "read"
  pull-requests: "read"
jobs:
  version-check:
    name: "VersionCheckNDTensors"
    uses: "ITensor/ITensorActions/.github/workflows/VersionCheck.yml@mf/subdir-inputs"
    with:
      subdir: "NDTensors"
      paths: "NDTensors"
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
